In [68]:
import pandas as pd

to_multi_dict = {
    0: (1, 1), 1: (0, 1), 2: (1, 2), 3: (0, 0),
    4: (0, 2), 5: (1, 0), 6: (0, 3), 7: (1, 3),
    8: (2, 1), 9: (3, 1), 10: (2, 0), 11: (4, 1),
    12: (2, 2), 13: (3, 2), 14: (2, 3), 15: (4, 2),
    16: (4, 0), 17: (3, 0), 18: (4, 3), 19: (3, 3)
} 
to_single_dict = {value:key for key, value in to_multi_dict.items()}

df = pd.read_csv('input/train/train_labels.txt', sep=' ', names=['file', 'plant', 'disease'], header=None)

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5)
df['label'] = df[['plant', 'disease']].apply(lambda x: to_single_dict[(x[0], x[1])], axis=1)
df["kfold"] = -1

df = df.sample(frac=0.05).reset_index(drop=True)
for fold, (trn_, val_) in enumerate(skf.split(X=df, y=df['label'])):
    print(len(trn_), len(val_))
    df.loc[val_, 'kfold'] = fold

df.to_csv('input/train_folds.csv', index=False)
df.shape

1279 320
1279 320
1279 320
1279 320
1280 319


(1599, 5)

In [69]:
import numpy as np

In [73]:
t1 = np.array([[1, 2, 3, 4], [1,2,3,4]])
t2 = np.array([[1, 2, 3, 4], [1,2,3,4]])
t3 = np.array([[1, 2, 3, 4], [1,2,3,4]])
t1 = np.array([1, 2, 3, 4])
t2 = np.array([1, 2, 3, 4])
t3 = np.array([1, 2, 3, 4])
tl = [t1, t2, t3]
tl

[array([1, 2, 3, 4]), array([1, 2, 3, 4]), array([1, 2, 3, 4])]

In [79]:
np.concatenate(tl, )

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

5116 1280
5117 1279
5117 1279
5117 1279
5117 1279


In [64]:
df = pd.read_csv('./input/train_folds.csv')

df_train = df[df['kfold'] != fold].reset_index(drop=True)
df_valid = df[df['kfold'] == fold].reset_index(drop=True)

In [65]:
df_train

file  plant  disease  label  kfold
0     19115.jpg      1        1      0      0
1     18488.jpg      1        2      2      0
2      9655.jpg      1        2      2      0
3     58495.jpg      0        1      1      0
4     44824.jpg      1        0      5      0
...         ...    ...      ...    ...    ...
5112   4204.jpg      3        1      9      3
5113  38996.jpg      3        1      9      3
5114  34191.jpg      3        1      9      3
5115  37904.jpg      2        3     14      3
5116  49899.jpg      4        0     16      3

[5117 rows x 5 columns]

In [57]:
df['file'].values.tolist()

['37432.jpg',
 '11457.jpg',
 '56809.jpg',
 '40176.jpg',
 '49767.jpg',
 '16854.jpg',
 '25713.jpg',
 '34009.jpg',
 '28452.jpg',
 '37418.jpg',
 '40669.jpg',
 '6212.jpg',
 '41843.jpg',
 '3470.jpg',
 '7749.jpg',
 '17986.jpg',
 '2872.jpg',
 '52366.jpg',
 '12212.jpg',
 '3561.jpg',
 '14363.jpg',
 '21278.jpg',
 '33921.jpg',
 '9091.jpg',
 '47675.jpg',
 '15129.jpg',
 '6257.jpg',
 '5532.jpg',
 '46842.jpg',
 '40657.jpg',
 '59714.jpg',
 '21998.jpg',
 '38017.jpg',
 '4709.jpg',
 '1646.jpg',
 '8365.jpg',
 '3191.jpg',
 '17936.jpg',
 '9239.jpg',
 '44915.jpg',
 '26133.jpg',
 '2093.jpg',
 '51501.jpg',
 '14609.jpg',
 '11997.jpg',
 '48994.jpg',
 '16418.jpg',
 '45949.jpg',
 '44442.jpg',
 '48679.jpg',
 '10433.jpg',
 '39239.jpg',
 '35570.jpg',
 '26267.jpg',
 '4079.jpg',
 '19752.jpg',
 '22644.jpg',
 '40528.jpg',
 '15359.jpg',
 '56291.jpg',
 '3881.jpg',
 '47190.jpg',
 '36422.jpg',
 '11491.jpg',
 '33458.jpg',
 '40375.jpg',
 '7524.jpg',
 '27380.jpg',
 '38938.jpg',
 '48942.jpg',
 '52582.jpg',
 '28931.jpg',
 '28581.j

In [1]:
to_multi_dict = {
    0: (1, 1), 1: (0, 1), 2: (1, 2), 3: (0, 0),
    4: (0, 2), 5: (1, 0), 6: (0, 3), 7: (1, 3),
    8: (2, 1), 9: (3, 1), 10: (2, 0), 11: (4, 1),
    12: (2, 2), 13: (3, 2), 14: (2, 3), 15: (4, 2),
    16: (4, 0), 17: (3, 0), 18: (4, 3), 19: (3, 3)
}  

In [ ]:
[[0,0,1,0,4]]

In [5]:
to_single_dict = {value:key for key, value in to_multi_dict.items()}

def to_multi_label(label):
    return to_multi_dict[label]


def to_single_label(label):
    return to_single_dict[label]


In [12]:
print(to_multi_label(1))
print(to_single_label((0,1)))

(0, 1)
1


In [27]:
import torch

preds = torch.tensor([1, 0, 2, 3, 4, 0, 1, 0])
preds

tensor([1, 0, 2, 3, 4, 0, 1, 0])

In [33]:
from sklearn.metrics import hamming_loss

In [44]:
converted = []
for i in preds:
    print(to_multi_label(i.item()))
    converted.append(to_multi_label(i.item()))

converted = torch.tensor(converted).numpy()
converted

(0, 1)
(1, 1)
(1, 2)
(0, 0)
(0, 2)
(1, 1)
(0, 1)
(1, 1)


array([[0, 1],
       [1, 1],
       [1, 2],
       [0, 0],
       [0, 2],
       [1, 1],
       [0, 1],
       [1, 1]])

In [103]:
plant = torch.tensor([1, 0, 0, 1])
disease = torch.tensor([3, 3, 0, 1])
labels = torch.stack([plant, disease], 1).numpy()
labels

array([[1, 3],
       [0, 3],
       [0, 0],
       [1, 1]])

In [105]:
outputs = torch.tensor([[ 0.7720,  0.4315, -0.1656,  0.3611, -0.0174,  0.3900, -0.2876, -0.6492,
             -0.1102, -0.7615, -0.6320, -0.4441, -0.3660, -0.5327, -0.4215],
        [ 0.6881, -0.1136,  0.1896,  1.7900, -0.0628, -1.3588, -0.3953, -0.5977,
         -0.1905, -0.6371, -0.4053, -0.4300, -0.4487, -0.3994, -0.2362],
        [ 0.6740,  0.3783, -0.1375,  0.4170,  0.1359,  0.2389, -0.3898, -0.6031,
         -0.0760, -0.6946, -0.6703, -0.4066, -0.3344, -0.5917, -0.4001],
        [ 1.2386,  0.3176, -0.1694, -1.0715, -0.0833,  2.7644, -0.5077, -0.7475,
         -0.0086, -1.0449, -0.9783, -0.5855, -0.3700, -0.7392, -1.0741]])

torch.Size([4, 15])

In [106]:
_, preds = torch.max(outputs, 1)
preds

tensor([0, 3, 0, 5])

In [111]:
converted = []
for i in preds:
    print(to_multi_label(i.item()))
    converted.append(to_multi_label(i.item()))

converted = np.asarray(converted)
    
preds_plant = converted[:,0]
preds_disease = converted[:,1]

(1, 1)
(0, 0)
(1, 1)
(1, 0)


In [112]:
preds_plant

array([1, 0, 1, 1])

In [113]:
preds_disease

array([1, 0, 1, 0])

In [100]:
plant = torch.tensor([1, 0, 0, 1])
disease = torch.tensor([3, 3, 0, 1])
labels = torch.stack([plant, disease], 1).numpy()
labels

array([[1, 3],
       [0, 3],
       [0, 0],
       [1, 1]])

In [114]:
def cal_hamming_loss(plant, disease, outputs):
    plant = plant.numpy()
    disease = disease.numpy()
    outputs = outputs.numpy()
    
    converted = []
    for i in outputs:
        converted.append(to_multi_label(i.item()))
    
    converted = np.asarray(converted)

    preds_plant = converted[:,0]
    preds_disease = converted[:,1]
    
    loss = (hamming_loss(plant, preds_plant) + hamming_loss(disease, preds_disease)) / 2
    return loss
    

In [115]:
cal_hamming_loss(plant, disease, preds)

0.625


In [92]:
plant.numpy()

array([0, 5, 1, 4, 0, 2, 1, 0])

In [95]:
num = np.max(plant.numpy()) + 1
encoding = np.eye(num)[plant.numpy()]
encoding

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [97]:
encoding

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [98]:
hamming_loss(encoding, encoding)

0.0

In [ ]:
encoding

In [96]:
plant.numpy()

array([0, 5, 1, 4, 0, 2, 1, 0])

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
labels

array([[0, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0]])

In [54]:
converted

array([[0, 1],
       [1, 1],
       [1, 2],
       [0, 0],
       [0, 2],
       [1, 1],
       [0, 1],
       [1, 1]])

In [55]:
hamming_loss(labels, converted)

ValueError: Classification metrics can't handle a mix of multilabel-indicator and multiclass-multioutput targets

In [66]:
import numpy as np

hamming_loss(np.array([[1,0,1],
                       [0,0,1]]), np.zeros((2,3)))

0.5

tensor([1, 0, 2, 3, 4, 0, 1, 0])

In [45]:
import csv
import pandas as pd


data = pd.read_csv('./data/train.csv', sep = ",", dtype='unicode')



for i in range(len(data['image_path'])):
    data['image_path'][i] = data['image_path'][i].rsplit('/', 1)[-1]


print(data['gender'].unique())
print(data['season'].unique())

data['gender'] = pd.factorize(data['gender'])[0]
data['season'] = pd.factorize(data['season'])[0]

print(data)

data = data[data['season'] != -1]

data.to_csv('train_labels1.txt', index=False, header=None, sep=" ")




['Women' 'Men' 'Unisex' 'Boys' 'Girls']
['Winter' 'Summer' 'Fall' 'Spring' nan]
      image_path  gender  season
0      23737.jpg       0       0
1      25077.jpg       1       0
2      34345.jpg       1       1
3      15266.jpg       0       2
4      15972.jpg       1       2
...          ...     ...     ...
31995  38938.jpg       3       1
31996   9432.jpg       1       1
31997   8838.jpg       1       1
31998  22981.jpg       1       2
31999  34171.jpg       3       1

[32000 rows x 3 columns]


In [23]:
import numpy as np

In [25]:
data['gender'].value_counts()

1    15902
0    13451
2     1587
3      579
4      481
Name: gender, dtype: int64

In [26]:
data['season'].value_counts()

 1    15493
 2     8288
 0     6043
 3     2157
-1       19
Name: season, dtype: int64

In [29]:
data = data[data['season'] != -1]

In [30]:
data.shape

(31981, 3)

In [34]:
value = (data.iloc[:,1].values, data.iloc[:,2].values)

In [39]:
data['tuple'] = data[['gender', 'season']].apply(lambda x: (x[0], x[1]), axis=1)

/home/youngwoon/anaconda3/envs/yolact/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [44]:
{i: v for i,v in enumerate(data['tuple'].value_counts().index)}

{0: (1, 1),
 1: (0, 1),
 2: (1, 2),
 3: (0, 0),
 4: (0, 2),
 5: (1, 0),
 6: (0, 3),
 7: (1, 3),
 8: (2, 1),
 9: (3, 1),
 10: (2, 0),
 11: (4, 1),
 12: (2, 2),
 13: (3, 2),
 14: (2, 3),
 15: (4, 2),
 16: (4, 0),
 17: (3, 0),
 18: (4, 3),
 19: (3, 3)}

In [2]:
a = [1,2,3,4,4]

set(a)

{1, 2, 3, 4}